from run_all_ccfs import *
#species_dict = {'Cu I' : {'vmr' : 2.06e-8},
#                'Cr I' : {'vmr' : 7.08e-07},
#                'Cr II' : {'vmr' : 7.08e-07},
#                'Ca I' : {'vmr' : 2.46e-06},
#                'Ba I' : {'vmr' : 3.20e-10},
#                'Zr II' : {'vmr' : 6.68e-10},
#                'Zr I' : {'vmr' : 6.68e-10},
#                'Zn I' : {'vmr' : 6.23e-8},
#                'Y II' : {'vmr' : 2.78e-10},
#                'Y I' : {'vmr' : 2.78e-10},
#                'W I' : {'vmr' : 1.06e-11},
#                'Tl I' : {'vmr' : 1.428e-11},
#                'Ti I' : {'vmr' : 5.63e-9},
#                'Ti II' : {'vmr' : 5.63e-9},
#                'Sr I' : {'vmr' : 1.16e-9},
#                'Sr II' : {'vmr' : 1.16e-9},
#                'Sn I' : {'vmr' : 1.80e-10},
#                'Sc I' : {'vmr' : 2.37e-9},
#                'Sc II' : {'vmr' : 2.37e-9},
#                'Ru I' : {'vmr' : 9.65e-11},
#                'Rh' : {'vmr' : 1.03e-11},
#                'Pd I' : {'vmr' : 6.38e-11},
#                'Pb I' : {'vmr' : 1.53e-10},
#                'Os I' : {'vmr' : 3.84e-11},
#                'O I' : {'vmr' : 1.81e-12},
#                'Mo I' : {'vmr' : 1.30e-10},
#                'Mn I' : {'vmr' : 2.31e-7},
#                'Ir' : {'vmr' : 3.59e-11},
#                'In I' : {'vmr' : 1.08e-11},
#                'Hf I' : {'vmr' : 1.22e-11},
#                'Ge I' : {'vmr' : 7.15e-9},
#                'Ga I' : {'vmr' : 1.80e-9}}

species_dict = {'Cu I' : {'vmr' : 2.06e-8},
                'Cr II' : {'vmr' : 7.08e-07},
                'Ca I' : {'vmr' : 2.46e-06},
                'Zr II' : {'vmr' : 6.68e-10},
                'Zr I' : {'vmr' : 6.68e-10},
                'Zn I' : {'vmr' : 6.23e-8},
                'W I' : {'vmr' : 1.06e-11},
                'Tl I' : {'vmr' : 1.428e-11},
                'Ti II' : {'vmr' : 5.63e-9},
                'Sr I' : {'vmr' : 1.16e-9},
                'Sr II' : {'vmr' : 1.16e-9},
                'Sc I' : {'vmr' : 2.37e-9},
                'Sc II' : {'vmr' : 2.37e-9},
                'Ru I' : {'vmr' : 9.65e-11},
                'Rh I' : {'vmr' : 1.03e-11},
                'Pb I' : {'vmr' : 1.53e-10},
                'Os I' : {'vmr' : 3.84e-11},
                'Mo I' : {'vmr' : 1.30e-10},
                'Mn I' : {'vmr' : 2.31e-7},
                'Ir I' : {'vmr' : 3.59e-11},
                'In I' : {'vmr' : 1.08e-11},
                'Hf I' : {'vmr' : 1.22e-11},
                'Ge I' : {'vmr' : 7.15e-9},
                'Ga I' : {'vmr' : 1.80e-9}}

multiSpeciesCCF('KELT-20b', 'inverted-transmission-better', species_dict, False, True, True, 'ccf')